import { HERO_DEFAULT_TRAJECTORY } from "@/hero-wave-background";
import { LAB_MATERIAL_LAYERS, SVG_LOOP } from "./constants";
import { createLabDeformer, createSceneFilament } from "./factories";
import type { LabState } from "./types";

const INITIAL_STATE_BASE: LabState = {
  theme: "dark",
  quality: "high",
  qualityAdvanced: false,
  qualityConfig: {
    maxDpr: 1.5,
    maxFps: 60,
    flatnessPx: 0.08,
    maxChordPx: 2.5,
    maxSamples: 32768,
    maxSubdivisionDepth: 18,
    farScale: 0.0625,
    midScale: 0.25,
    coreScale: 1,
    farMaxDimension: 1024,
    midMaxDimension: 2048,
    coreMaxDimension: 4096,
    farMaxChordPx: 96,
    midMaxChordPx: 48,
    coreMaxChordPx: 12,
    farFlatnessPx: 4,
    midFlatnessPx: 1,
    coreFlatnessPx: 0.2,
    quadrature: 4,
  },
  pathMode: "organic",
  textMode: false,
  text: "REPLAY",
  textHeight: 0.3,
  textLetterSpacing: 0.2,
  textY: 0.5,
  textHueSpread: 8,
  textStagger: 0.08,
  interpolation: "centripetal-catmull-rom",
  pathTension: 0,
  closed: false,
  closedLoopTaper: true,
  pathPoints: HERO_DEFAULT_TRAJECTORY.map((point) => ({ ...point })),
  svgPath: SVG_LOOP,
  svgViewBox: [0, 0, 200, 110],
  organic: {
    seed: 731,
    pointCount: 18,
    turns: 1.55,
    amplitude: 0.92,
    roughness: 0.28,
    horizontalJitter: 0.14,
    speedVariation: 0.7,
    symmetry: 0,
  },
  transform: {
    x: 0,
    y: 0,
    scaleX: 1,
    scaleY: 1,
    rotation: 0,
    anchorX: 0.5,
    anchorY: 0.5,
  },
  shape: {
    waveY: 0.68,
    strength: 1,
    scale: 0.62,
    frequency: 1.4,
  },
  motion: {
    mode: "travel",
    curveTravel: 0.08,
    pathDrift: 0,
    curveMotion: 0.65,
    segmentLength: 0.78,
    tailTaper: 0.24,
    headTaper: 0.14,
    speed: 0.7,
  },
  propagationEnabled: false,
  propagationPhaseOffset: 0,
  propagationPhaseSpeed: 1,
  propagationDeformers: [createLabDeformer("harmonics", 0)],
  propagationDomain: "arcLength",
  propagationCombine: "add",
  propagationStage: "after-follow",
  recomputeArcLength: false,
  profilePreset: "flat",
  profileSource: "preset",
  profileInterpolation: "cubic",
  profileWrap: "clamp",
  profileKeys: [
    {
      id: "profile-start",
      position: 0,
      width: 0.35,
      opacity: 0,
      intensity: 0.2,
      glow: 0.45,
      upperGlowSpread: 1,
      lowerGlowSpread: 1,
      reflection: 0.25,
      colorPosition: 0,
    },
    {
      id: "profile-middle",
      position: 0.5,
      width: 1,
      opacity: 1,
      intensity: 1,
      glow: 1.25,
      upperGlowSpread: 1,
      lowerGlowSpread: 1,
      reflection: 1,
      colorPosition: 0.08,
    },
    {
      id: "profile-end",
      position: 1,
      width: 0.35,
      opacity: 0,
      intensity: 0.2,
      glow: 0.45,
      upperGlowSpread: 1,
      lowerGlowSpread: 1,
      reflection: 0.25,
      colorPosition: 0,
    },
  ],
  profileStrength: 1,
  profileWidth: 1,
  profileOpacity: 1,
  profileIntensity: 1,
  profileGlow: 1,
  profileUpperGlowSpread: 1,
  profileLowerGlowSpread: 1,
  profileReflection: 1,
  profileColorPosition: 0,
  materialPreset: "soft-aurora",
  materialAdvanced: false,
  materialAtmosphere: LAB_MATERIAL_LAYERS["soft-aurora"].atmosphere,
  materialBroad: LAB_MATERIAL_LAYERS["soft-aurora"].broad,
  materialBody: LAB_MATERIAL_LAYERS["soft-aurora"].body,
  materialRidge: LAB_MATERIAL_LAYERS["soft-aurora"].ridge,
  materialCore: LAB_MATERIAL_LAYERS["soft-aurora"].core,
  materialVeil: LAB_MATERIAL_LAYERS["soft-aurora"].veil,
  materialIntensity: 1,
  materialGlow: 1,
  materialExposure: 1,
  materialSaturation: 1,
  upperGlowSpread: 1,
  lowerGlowSpread: 1,
  glowAsymmetry: 1,
  paletteStops: [
    { id: "blue", color: "#2438ff", offset: 0, easing: "smooth" },
    { id: "cyan", color: "#1adff5", offset: 0.22, easing: "smooth" },
    { id: "green", color: "#22f25f", offset: 0.82, easing: "smooth" },
    { id: "white", color: "#eaffff", offset: 1, easing: "linear" },
  ],
  paletteInterpolation: "oklab",
  paletteWrap: "repeat",
  paletteReverse: false,
  paletteSpeed: 1,
  hue: 0,
  hueDrift: 0,
  followMode: "hybrid",
  followActivation: "path-mode",
  followTransitionDuration: 0.48,
  followTarget: "window",
  followPointerMouse: true,
  followPointerPen: true,
  followPointerTouch: true,
  followExternalEnabled: false,
  followExternalSpace: "normalized",
  followExternalX: 0.5,
  followExternalY: 0.5,
  followLeaveBehavior: "idle",
  followHeadResponse: 1,
  followMemorySeconds: 1.05,
  followStationaryBehavior: "collapse",
  followStationaryCollapseDuration: 1.2,
  followLengthCssPx: 1500,
  followViscosity: 0.45,
  followCascadeLag: 0.45,
  followFadeDuration: 0.35,
  followIdleDelay: 0.45,
  followIdleRadiusX: 120,
  followIdleRadiusY: 75,
  followIdleSpeedX: 0.52,
  followIdleSpeedY: 0.41,
  followVelocityIntensity: 0.12,
  followVelocityWidth: 0.09,
  followVelocityGlow: 0.12,
  followVelocityHue: 9.6,
  followVelocityReflection: 0.12,
  followVelocityResponse: 14,
  followMaxVelocityCssPx: 1500,
  filamentInteractionEnabled: false,
  filamentInteractionTarget: "canvas",
  filamentInteractionMouse: true,
  filamentInteractionPen: true,
  filamentInteractionTouch: true,
  filamentInteractionRadius: 80,
  filamentInteractionStrength: 0.045,
  filamentInteractionPropagationSpeed: 0.72,
  filamentInteractionFrequency: 2.8,
  filamentInteractionDamping: 2.2,
  filamentInteractionSpatialDecay: 0.8,
  filamentInteractionDuration: 2.4,
  filamentInteractionCooldown: 0.07,
  filamentInteractionMaxImpulses: 8,
  filamentInteractionDirection: "push",
  dotsEnabled: true,
  dotMode: "flat",
  dotSpacing: 26,
  dotOpacity: 0.45,
  twinkle: 0.6,
  reflect: 0.8,
  dotInteractionEnabled: false,
  dotInteractionRadius: 140,
  dotInteractionSoftness: 0.55,
  dotInteractionBrightness: 1.1,
  dotInteractionColor: "#1adff5",
  dotInteractionColorStrength: 0.65,
  dotInteractionMagnification: 1.55,
  terrainPointerDisplacement: 0.55,
  maskFeather: 0.55,
  dotMasks: [
    { id: "left", x: 0.26, y: 0.52, radius: 0.72, feather: 0.55 },
    { id: "right", x: 0.78, y: 0.5, radius: 0.74, feather: 0.55 },
  ],
  terrainColumns: 112,
  terrainRows: 72,
  terrainWidth: 7.2,
  terrainDepth: 6.2,
  terrainAmplitude: 0.42,
  terrainPointSize: 2.1,
  terrainSpeed: 0.28,
  terrainViewAngle: 52,
  terrainCameraDistance: 3.2,
  terrainFrequency: 1.5,
  terrainOpacity: 0.52,
  terrainEdgeFade: 0.12,
  terrainFit: "fixed",
  terrainContentFade: 0.48,
  terrainColorLow: "#2438ff",
  terrainColorHigh: "#22f25f",
  backgroundImageSrc: "",
  backgroundImageFit: "cover",
  backgroundImageOpacity: 1,
  musicVisualizerEnabled: false,
  musicVisualizerSource: "element",
  musicAudioSrc: "",
  musicFftSize: 1024,
  musicSmoothing: 0.78,
  musicSensitivity: 1,
  musicBand: "energy",
  musicDeformation: 0.035,
  musicDeformationFrequency: 3,
  musicWidth: 0.18,
  musicIntensity: 0.3,
  musicGlow: 0.28,
  musicHue: 10,
  musicReflection: 0.2,
  glassTextEnabled: false,
  glassShape: "text",
  glassText: "Replay the market.\nProve the strategy.",
  glassDomTargetEnabled: false,
  glassDomSyncContent: true,
  glassDomSyncTypography: true,
  glassDomPaddingX: 12,
  glassDomPaddingY: 5,
  glassSvgPath: SVG_LOOP,
  glassSvgViewBox: [0, 0, 200, 110],
  glassFontSize: 96,
  glassCenterX: 50,
  glassCenterY: 50,
  glassMaxWidth: 0.82,
  glassMaxHeight: 0.42,
  glassRefraction: 18,
  glassEdgeWrap: 0,
  glassSurfaceModel: "volumetric",
  glassBevelMode: "biconvex",
  glassSurfaceDepth: 40,
  glassIor: 1.5,
  glassMagnification: 1.1,
  glassMagnificationY: 1.1,
  glassDisplacementX: 0,
  glassDisplacementY: 0,
  glassDiffusion: 0.72,
  glassBlur: 0.2,
  glassDistortion: 0.04,
  glassChromaticAberration: 2.4,
  glassFrost: 0.08,
  glassRoughness: 0.18,
  glassBevel: 1,
  glassRibStrength: 0,
  glassRibWidth: 18,
  glassRibAngle: -18,
  glassLiquidStrength: 0,
  glassLiquidScale: 3.2,
  glassLiquidSpeed: 0.22,
  glassEdgeStrength: 0.72,
  glassSpecular: 0.68,
  glassFresnel: 0.5,
  glassTwinkle: 0,
  glassTwinkleDensity: 0.28,
  glassTwinkleSpeed: 0.8,
  glassTwinkleSize: 28,
  glassTint: "#dffcff",
  glassTintStrength: 0.08,
  glassSaturation: 0,
  glassBrightness: 0,
  glassOpacity: 0.92,
  glassIntroDelay: 120,
  glassIntroDuration: 600,
  glassIntroBlur: 12,
  glassIntroOffsetY: 16,
  glassIntroCurvePreset: "custom",
  glassIntroCurve: [0.21, 0.47, 0.32, 0.98],
  sceneMode: false,
  primaryFilamentEnabled: true,
  primaryFilamentTimeOffset: 0,
  primaryFilamentPlaybackRate: 1,
  sceneFilaments: [],
  fadeInDuration: 900,
  fadeCurvePreset: "ease-out",
  fadeCurve: [0.16, 1, 0.3, 1],
  fadeInAffectsGlassText: false,
  paused: false,
  controlledTime: false,
  initialTime: 0,
  timelineTime: 2,
  playbackRate: 1,
  respectReducedMotion: true,
  pauseWhenOffscreen: true,
};

export const INITIAL_STATE: LabState = {
  ...INITIAL_STATE_BASE,
  sceneFilaments: [createSceneFilament(0, INITIAL_STATE_BASE)],
};
